print("Olá, mundo")
print("me chamo Júlia")
print("tenho 18 anos")
print("trabalho na IQVIA")
print("curso publicidade na UNISA")
print("minha cor favorita é roxo")
print("minha banda favorita e One Direction")
print("minha comida favorita é macarrão")
print("meu passatempo favorito é ir em shows")
print("estou com fome")